# Generated by Django 5.0.4 on 2024-04-13 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='linked',
            new_name='liked',
        ),
    ]
